In [1]:
import numpy as np

如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相同，且各维度的长度相同。

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = a * b
print (c)

[ 10  40  90 160]


当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制。

In [3]:
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([1, 2, 3])

print("a.shape = {}".format(a.shape))
print("b.shape = {}".format(b.shape))
print(a + b)

a.shape = (4, 3)
b.shape = (3,)
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [4]:
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([[1],
              [2],
              [3],
              [4]])

print("a.shape = {}".format(a.shape))
print("b.shape = {}".format(b.shape))

print(a + b)

a.shape = (4, 3)
b.shape = (4, 1)
[[ 1  1  1]
 [12 12 12]
 [23 23 23]
 [34 34 34]]
