In [1]:
import numpy as np

In [2]:
np.random.seed(666)  # set random seed

al = np.random.randn(4, 3)
print("al: {} \n".format(al))

# 对第 l 层进行dropout
keep_prob = 0.8
dl = np.random.rand(al.shape[0], al.shape[1])
print("dl: {}".format(dl))

al: [[ 0.82418808  0.479966    1.17346801]
 [ 0.90904807 -0.57172145 -0.10949727]
 [ 0.01902826 -0.94376106  0.64057315]
 [-0.78644317  0.60886999 -0.93101185]] 

dl: [[0.29322811 0.77447945 0.00510884]
 [0.11285765 0.11095367 0.24766823]
 [0.0232363  0.72732115 0.34003494]
 [0.19750316 0.90917959 0.97834699]]


In [3]:
dl = dl < keep_prob
print("dl: {}".format(dl))

dl: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True False False]]


In [4]:
al = np.multiply(al, dl)
print("al: {}".format(al))

al: [[ 0.82418808  0.479966    1.17346801]
 [ 0.90904807 -0.57172145 -0.10949727]
 [ 0.01902826 -0.94376106  0.64057315]
 [-0.78644317  0.         -0.        ]]
